/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { AddRecipients200Share } from "./addRecipients200Share";

export type AddRecipients200 = {
  share: AddRecipients200Share;
};
