/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { CheckFile201File } from "./checkFile201File";

export type CheckFile201 = {
  file: CheckFile201File;
  /** The file check message */
  message: string;
};
