/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { CreateShareAlias200Alias } from "./createShareAlias200Alias";

export type CreateShareAlias200 = {
  alias: CreateShareAlias200Alias;
};
