/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */

export type GetAppInfo200 = {
  /** The application name */
  appName: string;
  /** The application description */
  appDescription: string;
  /** The application logo */
  appLogo: string;
  /** The application first Access */
  firstUserAccess: boolean;
};
