/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { GetAllConfigs200ConfigsItem } from "./getAllConfigs200ConfigsItem";

export type GetAllConfigs200 = {
  configs: GetAllConfigs200ConfigsItem[];
};
