/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { GetCurrentUser200User } from "./getCurrentUser200User";

export type GetCurrentUser200 = {
  user: GetCurrentUser200User;
};
