/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */

export type GetPresignedUrl200 = {
  /** The pre-signed URL */
  url: string;
  /** The object name of the file */
  objectName: string;
};
