/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */

export type GetPresignedUrlParams = {
  /**
   * The filename of the file
   */
  filename: string;
  /**
   * The extension of the file
   */
  extension: string;
};
