/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { GetShare200ShareAlias } from "./getShare200ShareAlias";
import type { GetShare200ShareFilesItem } from "./getShare200ShareFilesItem";
import type { GetShare200ShareRecipientsItem } from "./getShare200ShareRecipientsItem";
import type { GetShare200ShareSecurity } from "./getShare200ShareSecurity";

export type GetShare200Share = {
  /** The share ID */
  id: string;
  /**
   * The share name
   * @nullable
   */
  name: string | null;
  /**
   * The share description
   * @nullable
   */
  description: string | null;
  /**
   * The share expiration date
   * @nullable
   */
  expiration: string | null;
  /** The number of views */
  views: number;
  /** The share creation date */
  createdAt: string;
  /** The share update date */
  updatedAt: string;
  /** The creator ID */
  creatorId: string;
  security: GetShare200ShareSecurity;
  files: GetShare200ShareFilesItem[];
  recipients: GetShare200ShareRecipientsItem[];
  /** @nullable */
  alias: GetShare200ShareAlias;
};
