/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { GetShareByAlias200Share } from "./getShareByAlias200Share";

export type GetShareByAlias200 = {
  share: GetShareByAlias200Share;
};
