/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { GetShare200Share } from "./getShare200Share";

export type GetShare200 = {
  share: GetShare200Share;
};
