/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */

export type LoginBody = {
  /** User email or username */
  emailOrUsername: string;
  /**
   * User password
   * @minLength 8
   */
  password: string;
};
