/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { RegisterUser201User } from "./registerUser201User";

export type RegisterUser201 = {
  user: RegisterUser201User;
  /** User registration message */
  message: string;
};
