/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */

export type RegisterFileBody = {
  /** @minLength 1 */
  name: string;
  description?: string;
  /** @minLength 1 */
  extension: string;
  size: number;
  /** @minLength 1 */
  objectName: string;
};
