/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */

export type RegisterUserBody = {
  /**
   * User first name
   * @minLength 1
   */
  firstName: string;
  /**
   * User last name
   * @minLength 1
   */
  lastName: string;
  /**
   * User username
   * @minLength 3
   */
  username: string;
  /** User email */
  email: string;
  /** User profile image URL */
  image?: string;
  /**
   * User password
   * @minLength 8
   */
  password: string;
};
