/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { RemoveRecipients200Share } from "./removeRecipients200Share";

export type RemoveRecipients200 = {
  share: RemoveRecipients200Share;
};
