/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { RemoveRecipients200ShareAlias } from "./removeRecipients200ShareAlias";
import type { RemoveRecipients200ShareFilesItem } from "./removeRecipients200ShareFilesItem";
import type { RemoveRecipients200ShareRecipientsItem } from "./removeRecipients200ShareRecipientsItem";
import type { RemoveRecipients200ShareSecurity } from "./removeRecipients200ShareSecurity";

export type RemoveRecipients200Share = {
  /** The share ID */
  id: string;
  /**
   * The share name
   * @nullable
   */
  name: string | null;
  /**
   * The share description
   * @nullable
   */
  description: string | null;
  /**
   * The share expiration date
   * @nullable
   */
  expiration: string | null;
  /** The number of views */
  views: number;
  /** The share creation date */
  createdAt: string;
  /** The share update date */
  updatedAt: string;
  /** The creator ID */
  creatorId: string;
  security: RemoveRecipients200ShareSecurity;
  files: RemoveRecipients200ShareFilesItem[];
  recipients: RemoveRecipients200ShareRecipientsItem[];
  /** @nullable */
  alias: RemoveRecipients200ShareAlias;
};
