/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */

export type RemoveAvatar200 = {
  id: string;
  firstName: string;
  lastName: string;
  username: string;
  email: string;
  /** @nullable */
  image: string | null;
  isAdmin: boolean;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
};
