/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateSharePassword200Share } from "./updateSharePassword200Share";

export type UpdateSharePassword200 = {
  share: UpdateSharePassword200Share;
};
