/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateConfig200Config } from "./updateConfig200Config";

export type UpdateConfig200 = {
  config: UpdateConfig200Config;
};
