/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateSharePassword200ShareAlias } from "./updateSharePassword200ShareAlias";
import type { UpdateSharePassword200ShareFilesItem } from "./updateSharePassword200ShareFilesItem";
import type { UpdateSharePassword200ShareRecipientsItem } from "./updateSharePassword200ShareRecipientsItem";
import type { UpdateSharePassword200ShareSecurity } from "./updateSharePassword200ShareSecurity";

export type UpdateSharePassword200Share = {
  /** The share ID */
  id: string;
  /**
   * The share name
   * @nullable
   */
  name: string | null;
  /**
   * The share description
   * @nullable
   */
  description: string | null;
  /**
   * The share expiration date
   * @nullable
   */
  expiration: string | null;
  /** The number of views */
  views: number;
  /** The share creation date */
  createdAt: string;
  /** The share update date */
  updatedAt: string;
  /** The creator ID */
  creatorId: string;
  security: UpdateSharePassword200ShareSecurity;
  files: UpdateSharePassword200ShareFilesItem[];
  recipients: UpdateSharePassword200ShareRecipientsItem[];
  /** @nullable */
  alias: UpdateSharePassword200ShareAlias;
};
