/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { AddFiles200Share } from "./addFiles200Share";

export type AddFiles200 = {
  share: AddFiles200Share;
};
