/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { AddFiles200ShareAlias } from "./addFiles200ShareAlias";
import type { AddFiles200ShareFilesItem } from "./addFiles200ShareFilesItem";
import type { AddFiles200ShareRecipientsItem } from "./addFiles200ShareRecipientsItem";
import type { AddFiles200ShareSecurity } from "./addFiles200ShareSecurity";

export type AddFiles200Share = {
  /** The share ID */
  id: string;
  /**
   * The share name
   * @nullable
   */
  name: string | null;
  /**
   * The share description
   * @nullable
   */
  description: string | null;
  /**
   * The share expiration date
   * @nullable
   */
  expiration: string | null;
  /** The number of views */
  views: number;
  /** The share creation date */
  createdAt: string;
  /** The share update date */
  updatedAt: string;
  /** The creator ID */
  creatorId: string;
  security: AddFiles200ShareSecurity;
  files: AddFiles200ShareFilesItem[];
  recipients: AddFiles200ShareRecipientsItem[];
  /** @nullable */
  alias: AddFiles200ShareAlias;
};
