/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { BulkUpdateConfigs200ConfigsItem } from "./bulkUpdateConfigs200ConfigsItem";

export type BulkUpdateConfigs200 = {
  configs: BulkUpdateConfigs200ConfigsItem[];
};
