/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */

export type BulkUpdateConfigsBodyItem = {
  /** The config key */
  key: string;
  /** The config value */
  value: string;
};
