/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */

export type CreateShareBody = {
  /** The share name */
  name?: string;
  /** The share description */
  description?: string;
  expiration?: string;
  /** The file IDs */
  files: string[];
  /** The share password */
  password?: string;
  /**
   * The maximum number of views
   * @nullable
   */
  maxViews?: number | null;
  /** The recipient emails */
  recipients?: string[];
};
