/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { CreateShare201ShareAlias } from "./createShare201ShareAlias";
import type { CreateShare201ShareFilesItem } from "./createShare201ShareFilesItem";
import type { CreateShare201ShareRecipientsItem } from "./createShare201ShareRecipientsItem";
import type { CreateShare201ShareSecurity } from "./createShare201ShareSecurity";

export type CreateShare201Share = {
  /** The share ID */
  id: string;
  /**
   * The share name
   * @nullable
   */
  name: string | null;
  /**
   * The share description
   * @nullable
   */
  description: string | null;
  /**
   * The share expiration date
   * @nullable
   */
  expiration: string | null;
  /** The number of views */
  views: number;
  /** The share creation date */
  createdAt: string;
  /** The share update date */
  updatedAt: string;
  /** The creator ID */
  creatorId: string;
  security: CreateShare201ShareSecurity;
  files: CreateShare201ShareFilesItem[];
  recipients: CreateShare201ShareRecipientsItem[];
  /** @nullable */
  alias: CreateShare201ShareAlias;
};
