/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { CreateShare201Share } from "./createShare201Share";

export type CreateShare201 = {
  share: CreateShare201Share;
};
