/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteShare200Share } from "./deleteShare200Share";

export type DeleteShare200 = {
  share: DeleteShare200Share;
};
