/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteShare200ShareAlias } from "./deleteShare200ShareAlias";
import type { DeleteShare200ShareFilesItem } from "./deleteShare200ShareFilesItem";
import type { DeleteShare200ShareRecipientsItem } from "./deleteShare200ShareRecipientsItem";
import type { DeleteShare200ShareSecurity } from "./deleteShare200ShareSecurity";

export type DeleteShare200Share = {
  /** The share ID */
  id: string;
  /**
   * The share name
   * @nullable
   */
  name: string | null;
  /**
   * The share description
   * @nullable
   */
  description: string | null;
  /**
   * The share expiration date
   * @nullable
   */
  expiration: string | null;
  /** The number of views */
  views: number;
  /** The share creation date */
  createdAt: string;
  /** The share update date */
  updatedAt: string;
  /** The creator ID */
  creatorId: string;
  security: DeleteShare200ShareSecurity;
  files: DeleteShare200ShareFilesItem[];
  recipients: DeleteShare200ShareRecipientsItem[];
  /** @nullable */
  alias: DeleteShare200ShareAlias;
};
