/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */

export type GetDownloadUrl200 = {
  /** The download URL */
  url: string;
  /** The expiration time in seconds */
  expiresIn: number;
};
