/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */

export type GetDiskSpace200 = {
  /** The server disk size in GB */
  diskSizeGB: number;
  /** The server disk used in GB */
  diskUsedGB: number;
  /** The server disk available in GB */
  diskAvailableGB: number;
  /** Whether file upload is allowed */
  uploadAllowed: boolean;
};
