/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */

export type GetShare200ShareRecipientsItem = {
  /** The recipient ID */
  id: string;
  /** The recipient email */
  email: string;
  /** The recipient creation date */
  createdAt: string;
  /** The recipient update date */
  updatedAt: string;
};
