/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { ListUserShares200SharesItem } from "./listUserShares200SharesItem";

export type ListUserShares200 = {
  shares: ListUserShares200SharesItem[];
};
