/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { ListUserShares200SharesItemAlias } from "./listUserShares200SharesItemAlias";
import type { ListUserShares200SharesItemFilesItem } from "./listUserShares200SharesItemFilesItem";
import type { ListUserShares200SharesItemRecipientsItem } from "./listUserShares200SharesItemRecipientsItem";
import type { ListUserShares200SharesItemSecurity } from "./listUserShares200SharesItemSecurity";

export type ListUserShares200SharesItem = {
  /** The share ID */
  id: string;
  /**
   * The share name
   * @nullable
   */
  name: string | null;
  /**
   * The share description
   * @nullable
   */
  description: string | null;
  /**
   * The share expiration date
   * @nullable
   */
  expiration: string | null;
  /** The number of views */
  views: number;
  /** The share creation date */
  createdAt: string;
  /** The share update date */
  updatedAt: string;
  /** The creator ID */
  creatorId: string;
  security: ListUserShares200SharesItemSecurity;
  files: ListUserShares200SharesItemFilesItem[];
  recipients: ListUserShares200SharesItemRecipientsItem[];
  /** @nullable */
  alias: ListUserShares200SharesItemAlias;
};
