/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { ListFiles200FilesItem } from "./listFiles200FilesItem";

export type ListFiles200 = {
  files: ListFiles200FilesItem[];
};
