/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { RegisterFile201File } from "./registerFile201File";

export type RegisterFile201 = {
  file: RegisterFile201File;
  /** The file registration message */
  message: string;
};
