/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { RemoveFiles200Share } from "./removeFiles200Share";

export type RemoveFiles200 = {
  share: RemoveFiles200Share;
};
