/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { RemoveFiles200ShareAlias } from "./removeFiles200ShareAlias";
import type { RemoveFiles200ShareFilesItem } from "./removeFiles200ShareFilesItem";
import type { RemoveFiles200ShareRecipientsItem } from "./removeFiles200ShareRecipientsItem";
import type { RemoveFiles200ShareSecurity } from "./removeFiles200ShareSecurity";

export type RemoveFiles200Share = {
  /** The share ID */
  id: string;
  /**
   * The share name
   * @nullable
   */
  name: string | null;
  /**
   * The share description
   * @nullable
   */
  description: string | null;
  /**
   * The share expiration date
   * @nullable
   */
  expiration: string | null;
  /** The number of views */
  views: number;
  /** The share creation date */
  createdAt: string;
  /** The share update date */
  updatedAt: string;
  /** The creator ID */
  creatorId: string;
  security: RemoveFiles200ShareSecurity;
  files: RemoveFiles200ShareFilesItem[];
  recipients: RemoveFiles200ShareRecipientsItem[];
  /** @nullable */
  alias: RemoveFiles200ShareAlias;
};
