/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */

export type RemoveFiles200ShareSecurity = {
  /**
   * The maximum number of views
   * @nullable
   */
  maxViews: number | null;
  /** Whether the share has a password */
  hasPassword: boolean;
};
