/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateShare200Share } from "./updateShare200Share";

export type UpdateShare200 = {
  share: UpdateShare200Share;
};
