/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateFile200File } from "./updateFile200File";

export type UpdateFile200 = {
  file: UpdateFile200File;
  /** Success message */
  message: string;
};
