/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * 🌴 Palmr. API
 * API documentation for Palmr file sharing system
 * OpenAPI spec version: 1.0.0
 */

export type UpdateFile200File = {
  /** The file ID */
  id: string;
  /** The file name */
  name: string;
  /**
   * The file description
   * @nullable
   */
  description: string | null;
  /** The file extension */
  extension: string;
  /** The file size */
  size: string;
  /** The object name of the file */
  objectName: string;
  /** The user ID */
  userId: string;
  /** The file creation date */
  createdAt: string;
  /** The file last update date */
  updatedAt: string;
};
